# Generated by Django 6.1 on 2026-08-24 07:01

from django.db import migrations


def block_india(apps, schema_editor):
    BlockedCountry = apps.get_model('embargo', 'BlockedCountry')
    BlockedCountry.objects.get_or_create(country='India')


def unblock_india(apps, schema_editor):
    BlockedCountry = apps.get_model('embargo', 'BlockedCountry')
    BlockedCountry.objects.filter(country__iexact='India').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('embargo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(block_india, unblock_india),
    ]
