# Generated by Django 6.1 on 2026-08-24 07:01

from django.db import migrations


def block_india(apps, schema_editor):
    BlockedCountry = apps.get_model('embargo', 'BlockedCountry')
    db_alias = schema_editor.connection.alias
    if not BlockedCountry.objects.using(db_alias).filter(country__iexact='India').exists():
        BlockedCountry.objects.using(db_alias).create(country='India')


def unblock_india(apps, schema_editor):
    BlockedCountry = apps.get_model('embargo', 'BlockedCountry')
    db_alias = schema_editor.connection.alias
    BlockedCountry.objects.using(db_alias).filter(country__iexact='India').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('embargo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(block_india, unblock_india),
    ]
