[project]
name = "ai-on-boarding"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ibtisam Saeed", email = "138524458+ibtisam-saeed@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "fastmcp[apps]>=4.0.2",
    "httpx>=0.28.1",
]

[project.scripts]
ai-on-boarding = "ai_on_boarding:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
