"""
Django settings for sdd_django_demo project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-5)e59r^si84)73b(kqi!2-64cbji^ei0tvay_ptqt5djufq%@c'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'drf_spectacular',
    'api',
    'embargo',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    # Keyed on the submitted email address, not the caller: the harm this caps is
    # done to an account, and every request supersedes that account's previous
    # code. See the change's design.md.
    'DEFAULT_THROTTLE_RATES': {
        'password-reset': '5/hour',
    },
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'sdd_django_demo API',
    'DESCRIPTION': 'Spec-driven development worked example.',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sdd_django_demo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sdd_django_demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases
#
# Postgres in every environment (dev, test, and prod alike) - not just prod with a
# SQLite fallback for local work - so the database actually exercised by the test suite
# is the same engine running in production. Read from DATABASE_URL rather than discrete
# host/port/user/password settings: it's the de facto standard env var name across
# hosting providers, and just as easy to set by hand on a bare VM as separate variables
# would be, with one fewer name to keep in sync between them.

_database_url = os.environ.get('DATABASE_URL')
if not _database_url:
    raise RuntimeError(
        'DATABASE_URL is not set. This project requires Postgres in every environment - '
        'set it to a postgres connection string, e.g. '
        'postgres://user:password@localhost:5432/dbname.'
    )

_parsed_database_url = urlparse(_database_url)

if _parsed_database_url.scheme not in ('postgres', 'postgresql'):
    raise RuntimeError(
        f"DATABASE_URL has scheme {_parsed_database_url.scheme!r} - only postgres:// and "
        "postgresql:// are supported."
    )

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': _parsed_database_url.path.lstrip('/'),
        'USER': _parsed_database_url.username,
        'PASSWORD': _parsed_database_url.password,
        'HOST': _parsed_database_url.hostname,
        'PORT': _parsed_database_url.port or 5432,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# The console backend is the default so the project still runs, and the test suite
# still passes, with no environment set up at all - the reset link simply prints to
# the runserver terminal.
#
# Setting RESET_SMTP_HOST switches delivery to a real SMTP server instead. Nothing
# in the application changes: `send_reset_link` calls `send_mail` either way, and
# only the transport underneath it differs. Credentials are read from the
# environment rather than written here, because this file is tracked.

# Stripped for the same reason the port below is: a variable set to whitespace is
# truthy, so an unstripped host would switch the SMTP backend on with a host that
# cannot resolve. That failure is swallowed by `try_deliver_reset_link`, so it
# would surface as mail silently not arriving rather than as an error.
_SMTP_HOST = (os.environ.get('RESET_SMTP_HOST') or '').strip()

if _SMTP_HOST:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.smtp.EmailBackend',
            'OPTIONS': {
                'host': _SMTP_HOST,
                # Stripped, and `or 587` rather than a default argument: a variable
                # that is set but blank reaches this line as '' or '   ', and int()
                # raises on both at import, taking down the whole application rather
                # than only its mail.
                'port': int((os.environ.get('RESET_SMTP_PORT') or '').strip() or 587),
                'username': os.environ.get('RESET_SMTP_USER', ''),
                'password': os.environ.get('RESET_SMTP_PASSWORD', ''),
                # On unless explicitly turned off. Django's SMTP backend authenticates
                # whenever a username and password are set, encrypted or not, so a
                # default of off would put credentials on the wire for anyone who
                # pointed this at a real provider without reading this far. A local
                # catcher speaking plain SMTP is the case that has to ask, by setting
                # RESET_SMTP_TLS=0.
                'use_tls': os.environ.get('RESET_SMTP_TLS', '1') != '0',
                'timeout': 10,
            },
        },
    }
else:
    MAILERS = {
        'default': {
            'BACKEND': 'django.core.mail.backends.console.EmailBackend',
        },
    }

DEFAULT_FROM_EMAIL = os.environ.get('RESET_SMTP_FROM', 'no-reply@example.com')


# Password reset
#
# Where a reset link points. Deliberately a setting rather than something derived
# from the incoming request: the request that asks for a reset is made by whoever
# wants it, so trusting its Host would let an attacker aim a genuine reset mail at
# their own server. See the change's design.md for the full reasoning.

RESET_LINK_BASE_URL = 'http://localhost:8000'
