# Generated by Django 6.1 on 2026-08-22 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SigninAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_or_username', models.CharField(max_length=255, unique=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
