# Generated by Django 6.1 on 2026-08-23 17:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='passwordresetcode',
            constraint=models.UniqueConstraint(condition=models.Q(('usable', True)), fields=('user',), name='one_usable_reset_code_per_user'),
        ),
    ]
