# Generated by Django 6.1 on 2026-08-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_passwordresetcode_one_usable_reset_code_per_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigninAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_failed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
