# Generated by Django 6.1 on 2026-09-20 08:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_signinattempt_window_started_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinattempt',
            name='email_or_username',
            field=models.CharField(max_length=320, unique=True),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Use lowercase letters, digits and hyphens.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('join_code_digest', models.CharField(blank=True, default='', max_length=64)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9-]+$')), name='organization_slug_format')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=254)),
                ('username', models.CharField(max_length=150)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='memberships', to='api.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('organization', 'email'), name='membership_unique_org_email'), models.UniqueConstraint(fields=('organization', 'username'), name='membership_unique_org_username')],
            },
        ),
    ]
