# Generated by Django 6.1 on 2026-09-21 07:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_organization_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='organization',
            name='join_code_digest',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='organization',
            name='slug',
            field=models.SlugField(unique=True, validators=[django.core.validators.RegexValidator('^[a-z0-9-]+$', 'Use lowercase letters, digits and hyphens.')]),
        ),
    ]
