# Generated by Django 6.1 on 2026-09-22 08:07

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_builtin_field_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='membership',
            name='membership_unique_org_email',
        ),
        migrations.RemoveConstraint(
            model_name='membership',
            name='membership_unique_org_username',
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), models.F('organization'), condition=models.Q(('email', ''), _negated=True), name='membership_unique_org_email'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), models.F('organization'), name='membership_unique_org_username'),
        ),
    ]
